development:
  adapter: postgresql
  database: comiunidad_db_dev
  username: juanvelasquez
  password: valentina
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: comiunidad_db_test
  username: juanvelasquez
  password: valentina
  pool: 5
  timeout: 5000
  host: localhost

production:
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: <%= ENV['RDS_PORT'] %>
